#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail

exec 2>&1

kill -KILL -- "-$4" || true

tee <<- EOF
---------------------------------
Service $3 stopped (s6 status $1)
---------------------------------
EOF

if [[ ./data/.runner.sh -ef ./data/oneshot/.runner.sh ]]; then
  exit 125
fi
