#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail

if [[ -f data/pgid ]]; then
  GROUP="$(< data/pgid)"
  if ! kill -KILL -- "-$GROUP"; then
    if kill -0 -- "-$GROUP"; then
      exit 1
    fi
  fi
  rm -fr -- data/pgid
fi
