#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail

exec 2>&1

kill -KILL -- "-$4" || true

tee <<- EOF
---------------------------------
Service $3 stopped (s6 status $1)
---------------------------------
EOF

INSTANCE_DATA='./data'
if [[ $INSTANCE_DATA/.runner.sh -ef $INSTANCE_DATA/oneshot/.runner.sh ]]; then
  touch -- "../../data/done/$3"
  exit 125
fi
