---
services:
  watchtower:
    image: docker.io/containrrr/watchtower:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro

  ollama:
    image: docker.io/ollama/ollama:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 11434:11434
    volumes:
      - /media/shared/ollama:/root/.ollama

  tabby:
    image: docker.io/tabbyml/tabby:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      TABBY_WEBSERVER_JWT_TOKEN_SECRET:
    command:
      - serve
      - --device
      - cuda
      - --model
      - StarCoder-3B
    ports:
      - 6060:8080
    volumes:
      - /media/shared/tabby:/data

  traefik:
    image: docker.io/library/traefik:latest
    mem_swappiness: 0
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --spider
        - --timeout
        - "1"
        - --
        - localhost:8080
    labels:
      traefik.enable: true
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    ports:
      - 8888:8888
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./:/etc/traefik:ro

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      # NEXT_PUBLIC_BASE_PATH:
      ANTHROPIC_API_KEY:
      OPENAI_API_KEY:
    ports:
      - 8008:8080
    volumes:
      - openwebui:/app/backend/data

  lobe-chat:
    image: docker.io/lobehub/lobe-chat:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      # NEXT_PUBLIC_BASE_PATH:
      ANTHROPIC_API_KEY:
      OPENAI_API_KEY:
    ports:
      - 3210:3210

  perplexica-backend:
    image: docker.io/itzcrazykns1337/perplexica-backend:main
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      SEARXNG_API_URL:
    ports:
      - 3001:3001
    volumes:
      - perplexica:/home/perplexica/data
      - ./opt/perplexica/config.toml:/home/perplexica/config.toml

  perplexica-frontend:
    build:
      context: ./opt/perplexica/Perplexica
      dockerfile: app.dockerfile
      args:
        NEXT_PUBLIC_API_URL: &api_uri http://${HOSTNAME}:3001/api
        NEXT_PUBLIC_WS_URL: &ws_uri ws://${HOSTNAME}:3001
    # image: itzcrazykns1337/perplexica-frontend:main
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    depends_on:
      - perplexica-backend
    environment:
      NEXT_PUBLIC_API_URL: *api_uri
      NEXT_PUBLIC_WS_URL: *ws_uri
    ports:
      - 3000:3000

volumes:
  openwebui:
  perplexica:
