---
services:
  watchtower:
    image: docker.io/containrrr/watchtower:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro

  ollama:
    image: docker.io/ollama/ollama:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 11434:11434
    volumes:
      - /media/shared/ollama:/root/.ollama

  tabby:
    image: docker.io/tabbyml/tabby:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      TABBY_WEBSERVER_JWT_TOKEN_SECRET:
    command:
      - serve
      - --device
      - cuda
      - --model
      - StarCoder-3B
    ports:
      - 6060:8080
    volumes:
      - /media/shared/tabby:/data

  # open-webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   restart: unless-stopped
  #   labels:
  #     com.centurylinklabs.watchtower.enable: true
  #   environment:
  #     ANTHROPIC_API_KEY:
  #     OPENAI_API_KEY:
  #     WEBUI_AUTH: false
  #   ports:
  #     - 8008:8080
  #   volumes:
  #     - openwebui:/app/backend/data

  perplexica-api:
    image: docker.io/itzcrazykns1337/perplexica-backend:main
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      SEARXNG_API_URL:
    ports:
      - 3001:3001
    volumes:
      - perplexica:/home/perplexica/data
      - ./opt/perplexica/config.toml:/home/perplexica/config.toml

  perplexica-web:
    image: itzcrazykns1337/perplexica-frontend:main
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    depends_on:
      - perplexica-api

  perplexica-proxy:
    image: docker.io/nginx:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - 3000:80
    volumes:
      - ./proxy.nginx:/etc/nginx/conf.d/default.conf

volumes:
  openwebui:
  perplexica:
