#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail

SELF="$(realpath -- "$0")"
cd -P -- "$1"
shift -- 1

WANTS="$PWD/wants"
DEPTH="${1:-67}"
if (($# > 1)) || [[ $DEPTH != +([0-9]) ]]; then
  set -x
  exit 2
fi
DEPTH=$((10#$DEPTH))

TEE=(tee)
if [[ -t 1 ]]; then
  TEE=(tree --fromfile --noreport .)
fi

if ((DEPTH == 0)) || ! [[ -d $WANTS ]]; then
  exit
fi

cd -P -- "$WANTS"
find . -mindepth 1 -maxdepth 1 -type l -printf '%P\0' | sort --zero-terminated | while IFS= read -r -d '' REQUEST; do
  printf -- '%s\n' "$REQUEST"
  if ((DEPTH > 1)); then
    "$SELF" "$REQUEST" "$((DEPTH - 1))" | while IFS= read -r DEPENDENCY; do
      printf -- '%s/%s\n' "$REQUEST" "$DEPENDENCY"
    done
  fi
done | "${TEE[@]}"
