#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail

: "${S67_HARNESS_PID?}"
: "${S67_HARNESS_STARTED?}"

STATE="$(realpath -- "${0%/*}/../..")"

if STARTED="$(LC_ALL=C.UTF-8 ps -p "$S67_HARNESS_PID" -o lstart=)"; then
  if [[ $STARTED == "$S67_HARNESS_STARTED" ]]; then
    exit
  fi
fi

exec -- s6-svscanctl -t "$STATE"
