#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail
shopt -u failglob dotglob

ROOT="${0%/jobs/quine/run}"

if [[ ${RECUR:-} == 1 ]]; then
  JOB="$PWD/${1#./}"
  SOURCES=("$ROOT/base/./")
  if [[ -d $JOB/env ]]; then
    SOURCES+=("$JOB/./env")
  fi
  for REQUEST in "$JOB"/data/@(oneshot|recurring)/*; do
    if ! [[ -f $REQUEST ]]; then
      continue
    fi
    KIND="${REQUEST%/*}"
    KIND="${KIND##*/}"
    DEST="$2/${REQUEST##*/}"
    if [[ -d $DEST ]]; then
      continue
    fi
    rsync --archive --relative -- "${SOURCES[@]}" "$DEST/"
    ln -sf -- "$JOB/run" "$DEST/data/job"
    if [[ $KIND == recurring ]]; then
      ln -sf -- recurring/.runner.sh "$DEST/data/.runner.sh"
    fi
  done
  exit
fi

RECUR=1 find "$ROOT/jobs" -mindepth 1 -maxdepth 1 -type d -execdir "$0" '{}' "$PWD" ';'

if (($#)); then
  exec -- s6-svscanctl -h -- "$PWD"
fi
