#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail
shopt -u failglob

BASE="${0%/jobs/quine/run}"

if [[ ${RECUR:-} == 1 ]]; then
  REQUEST="$1"
  KIND="${REQUEST%/*}"
  JOB="${KIND%/data/*}"
  KIND="${KIND##*/}"
  NAME="${JOB##*/}:$KIND:${REQUEST##*/}"
  DEST="$PWD/$NAME"
  if [[ -d $DEST ]]; then
    exit
  fi
  rsync --archive --relative -- "$BASE/base/./" "$JOB/./"en[v] "$DEST/"
  ln -sf -- "$JOB/run" "$DEST/data/job"
  if [[ $KIND == recurring ]]; then
    ln -sf -- recurring/.runner.sh "$DEST/data/.runner.sh"
  fi
  exit
fi

find "$BASE/jobs" -mindepth 4 -maxdepth 4 -type f ! -name '.*' \( -path '*/data/oneshot/*' -o -path '*/data/recurring/*' \) -exec env RECUR=1 "$0" '{}' ';'

if (($#)); then
  exec -- s6-svscanctl -h "$PWD"
fi
