#!/usr/bin/env -S -- bash -Eeuo pipefail -O dotglob -O nullglob -O extglob -O failglob -O globstar

set -o pipefail

SERVICE="${PWD%/log}"
LOGS="../../../../log/job-${SERVICE##*/}.log"

mkdir -p -- "$LOGS"
exec -- s6-log -b T "$LOGS"
