---
on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          # TODO: version 3.13 is broken
          python-version: "3.12"

      - uses: actions/setup-node@v3

      - run: |-
          gmake lint

      - run: |-
          gmake fmt
          git diff --exit-code
