---
on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - uses: actions/setup-node@v4

      - run: |-
          gmake lint

      - run: |-
          gmake fmt
          git diff --exit-code
